# Generated by Django 5.0.1 on 2024-01-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="finished_at",
            field=models.DateTimeField(null=True),
        ),
    ]
